# Continuous Integration pipeline

trigger:
  batch: false
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: "nodejs.version"
    value: "14.x"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodejs.version)
    displayName: "Install Node.js $(nodejs.version)"

  - script: |
      npm i katacoda-cli --global
    displayName: "Install KataCoda CLI"

  - script: |
      katacoda validate:all --repo $(Build.SourcesDirectory)
    displayName: "Validate KataCoda scenarios"
